In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.decomposition import PCA

In [7]:
df = pd.read_csv("Student_Performance.csv")

df.head()

,student_id,age,gender,academic_level,study_hours,self_study_hours,online_classes_hours,social_media_hours,gaming_hours,sleep_hours,...,exercise_minutes,caffeine_intake_mg,part_time_job,upcoming_deadline,internet_quality,mental_health_score,focus_index,burnout_level,productivity_score,exam_score
0,1,18,Other,High School,7.64,1.56,2.20,3.05,2.19,6.52,...,81,38,1,0,Good,10,43.05,31.77,73.65,50.16
1,2,18,Other,High School,2.21,2.22,2.10,1.65,2.55,5.97,...,111,339,0,0,Good,3,15.92,37.00,13.70,1.00
2,3,22,Male,High School,3.45,0.00,0.29,1.34,2.08,8.39,...,68,266,0,1,Good,8,27.39,34.37,45.15,18.30
3,4,17,Other,High School,5.75,2.08,3.01,2.27,2.20,6.31,...,113,480,1,1,Poor,3,22.31,77.31,20.92,9.37
4,5,19,Other,High School,6.83,1.72,3.33,2.65,0.70,8.01,...,121,24,1,0,Good,8,38.11,39.53,59.23,27.81

In [8]:
#Task 1

df.info() # Check dataset info

df.isnull().sum() # Check missing values

df.duplicated().sum() # Check duplicate rows

df.describe() # Summary stats

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   student_id            5000 non-null   int64
 1   age                   5000 non-null   int64
 2   gender                5000 non-null   str
 3   academic_level        5000 non-null   str
 4   study_hours           5000 non-null   float64
 5   self_study_hours      5000 non-null   float64
 6   online_classes_hours  5000 non-null   float64
 7   social_media_hours    5000 non-null   float64
 8   gaming_hours          5000 non-null   float64
 9   sleep_hours           5000 non-null   float64
 10  screen_time_hours     5000 non-null   float64
 11  exercise_minutes      5000 non-null   int64
 12  caffeine_intake_mg    5000 non-null   int64
 13  part_time_job         5000 non-null   int64
 14  upcoming_deadline     5000 non-null   int64
 15  internet_quality      5000 non-null   str
 16  mental_health_score   5000 non-null   int64
 17  focus_index           5000 non-null   float64
 18  burnout_level         5000 non-null   float64
 19  productivity_score    5000 non-null   float64
 20  exam_score            5000 non-null   float64
dtypes: float64(11), int64(7), str(3)
memory usage: 820.4 KB

,student_id,age,study_hours,self_study_hours,online_classes_hours,social_media_hours,gaming_hours,sleep_hours,screen_time_hours,exercise_minutes,caffeine_intake_mg,part_time_job,upcoming_deadline,mental_health_score,focus_index,burnout_level,productivity_score,exam_score
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,2500.500000,20.520400,4.539594,2.478734,2.011984,2.998086,1.564514,7.016492,6.979588,74.535600,251.450400,0.498200,0.501400,5.507400,29.431616,45.615324,37.267716,18.803752
std,1443.520003,2.870406,1.821665,1.177990,0.983906,1.467949,1.110807,1.163692,2.486214,42.932293,143.842712,0.500047,0.500048,2.869145,9.962902,14.246591,16.849397,12.130840
min,1.000000,16.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,1250.750000,18.000000,3.250000,1.660000,1.320000,1.990000,0.670000,6.237500,5.280000,37.000000,129.000000,0.000000,0.000000,3.000000,22.567500,35.727500,25.290000,9.337500
50%,2500.500000,20.000000,4.530000,2.480000,2.010000,2.980000,1.490000,7.010000,6.950000,75.000000,252.000000,0.000000,1.000000,5.000000,29.430000,45.690000,36.860000,18.010000
75%,3750.250000,23.000000,5.760000,3.290000,2.690000,4.030000,2.340000,7.810000,8.710000,112.000000,376.000000,1.000000,1.000000,8.000000,36.242500,55.352500,49.142500,27.400000
max,5000.000000,25.000000,11.840000,7.410000,6.000000,8.280000,5.640000,10.000000,15.300000,149.000000,499.000000,1.000000,1.000000,10.000000,63.480000,97.580000,98.020000,64.090000

In [10]:
#Task 2
df_filled = df.fillna(df.mean(numeric_only=True)) #Missing value strategy

In [18]:
#Task 3

numeric_cols = df.select_dtypes(include=np.number).columns

outliers = {}

for col in numeric_cols:
    
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    
    IQR = Q3 - Q1
    
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    
    outliers[col] = df[(df[col] < lower) | (df[col] > upper)].shape[0]

outliers
for col in numeric_cols:
    
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    
    IQR = Q3 - Q1
    
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    
    df[col] = np.clip(df[col], lower, upper)

In [14]:
numeric_df = df.select_dtypes(include=np.number)
minmax_scaler = MinMaxScaler()

df_minmax = pd.DataFrame(
    minmax_scaler.fit_transform(numeric_df),
    columns=numeric_df.columns
)

df_minmax.head()

,student_id,age,study_hours,self_study_hours,online_classes_hours,social_media_hours,gaming_hours,sleep_hours,screen_time_hours,exercise_minutes,caffeine_intake_mg,part_time_job,upcoming_deadline,mental_health_score,focus_index,burnout_level,productivity_score,exam_score
0,0.0000,0.222222,0.802100,0.272014,0.463646,0.430183,0.452012,0.420000,0.425515,0.543624,0.076152,1.0,0.0,1.000000,0.749452,0.324586,0.865693,0.918986
1,0.0002,0.222222,0.232021,0.387097,0.442571,0.232722,0.526316,0.328333,0.392843,0.744966,0.679359,0.0,0.0,0.222222,0.253473,0.391210,0.151332,0.000000
2,0.0004,0.666667,0.362205,0.000000,0.061117,0.188999,0.429309,0.731667,0.514975,0.456376,0.533066,0.0,1.0,0.777778,0.463163,0.357707,0.526088,0.323402
3,0.0006,0.111111,0.603675,0.362685,0.634352,0.320169,0.454076,0.385000,0.830027,0.758389,0.961924,1.0,1.0,0.222222,0.370293,0.904713,0.237365,0.156467
4,0.0008,0.333333,0.717060,0.299913,0.701791,0.373766,0.144479,0.668333,0.701673,0.812081,0.048096,1.0,0.0,0.777778,0.659141,0.423439,0.693865,0.501180

In [19]:
#Z-Score normalization
scaler = StandardScaler()

df_zscore = pd.DataFrame(
    scaler.fit_transform(numeric_df),
    columns=numeric_df.columns
)

df_zscore.head()

,student_id,age,study_hours,self_study_hours,online_classes_hours,social_media_hours,gaming_hours,sleep_hours,screen_time_hours,exercise_minutes,caffeine_intake_mg,part_time_job,upcoming_deadline,mental_health_score,focus_index,burnout_level,productivity_score,exam_score
0,-1.731704,-0.878152,1.709405,-0.781277,0.192851,0.037061,0.566123,-0.426695,-0.204756,0.150587,-1.484064,1.003607,-1.002804,1.565989,1.370899,-0.974181,2.163148,2.591535
1,-1.731012,-0.878152,-1.282364,-0.219385,0.090857,-0.921187,0.891343,-0.899376,-0.373994,0.849432,0.608709,-0.996406,-1.002804,-0.874006,-1.359121,-0.606086,-1.400449,-1.470363
2,-1.730319,0.515519,-0.599161,-2.109384,-1.755234,-1.133370,0.466750,1.180420,0.258634,-0.152246,0.101159,-0.996406,0.997204,0.868848,-0.204926,-0.791189,0.469027,-0.040932
3,-1.729626,-1.226569,0.668071,-0.338574,1.019002,-0.496820,0.575157,-0.607173,1.890573,0.896021,1.589044,1.003607,0.997204,-0.874006,-0.716113,2.230987,-0.971272,-0.778783
4,-1.728933,-0.529734,1.263119,-0.645061,1.345383,-0.236724,-0.779926,0.853840,1.225709,1.082380,-1.581402,1.003607,-1.002804,0.868848,0.873800,-0.428021,1.305982,0.744842

In [20]:
#Task 5 - Apply PCA and Interpret Explained Variance
X = df_zscore

pca = PCA()

pca.fit(X)

explained_variance = pca.explained_variance_ratio_

explained_variance

array([0.20064998, 0.10363546, 0.06309108, 0.05934628, 0.05836463,
       0.05694861, 0.05677044, 0.05661717, 0.05544967, 0.054846  ,
       0.05354209, 0.0531069 , 0.05254582, 0.05131947, 0.00841349,
       0.00798796, 0.00479969, 0.00256528])